/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface StyleGuideRequestBody {
    /** The name of the style guide. */
    name?: string;
}
