/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface StyleGuidesListStyleGuidesRequest {
    offset?: number;
    limit?: number;
}
