/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../../../index";

export type StyleChecksGetStyleCheckResponse = acrolinx.StyleCheckResponse | acrolinx.WorkflowStatusResponse;
