/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Analysis {
    clarity_score?: number;
    word_count?: number;
    sentence_count?: number;
    avg_word_length?: number;
    avg_sentence_length?: number;
    flesch_reading_ease?: number;
    flesch_kincaid_grade?: number;
    lexical_diversity?: number;
    vocabulary_complexity?: number;
    sentence_complexity?: number;
    tone_score?: number;
    informality_score?: number;
    liveliness_score?: number;
}
