/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface CheckOptions {
    style_guide?: acrolinx.StyleGuide;
    dialect?: acrolinx.Dialects;
    tone?: acrolinx.Tones;
}
