/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClarityScore {
    score: number;
    word_count: number;
    sentence_count: number;
    average_sentence_length: number;
    flesch_reading_ease: number;
    flesch_kincaid_grade: number;
    lexical_diversity: number;
    vocabulary_complexity: number;
    sentence_complexity: number;
}
