/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ContentQualityFeedback =
    | "Excellent content quality! Your text is clear, readable, and well-structured."
    | "Good content quality. Your text is readable but has room for improvement."
    | "Moderate content quality. Consider revising for better readability."
    | "Low content quality. The text needs significant revision for better readability.";
export const ContentQualityFeedback = {
    ExcellentContentQualityYourTextIsClearReadableAndWellStructured:
        "Excellent content quality! Your text is clear, readable, and well-structured.",
    GoodContentQualityYourTextIsReadableButHasRoomForImprovement:
        "Good content quality. Your text is readable but has room for improvement.",
    ModerateContentQualityConsiderRevisingForBetterReadability:
        "Moderate content quality. Consider revising for better readability.",
    LowContentQualityTheTextNeedsSignificantRevisionForBetterReadability:
        "Low content quality. The text needs significant revision for better readability.",
} as const;
