/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ContentSuggestions =
    | "Use shorter sentences and simpler words to improve readability."
    | "Your text may be too complex. Consider simplifying vocabulary and sentence structure."
    | "Your sentences are quite long. Consider breaking them into shorter ones."
    | "Your sentences are very short. Consider combining some for better flow."
    | "Your vocabulary diversity is low. Try using a wider range of words."
    | "Your text is well-balanced. Consider proofreading for minor improvements.";
export const ContentSuggestions = {
    UseShorterSentencesAndSimplerWordsToImproveReadability:
        "Use shorter sentences and simpler words to improve readability.",
    YourTextMayBeTooComplexConsiderSimplifyingVocabularyAndSentenceStructure:
        "Your text may be too complex. Consider simplifying vocabulary and sentence structure.",
    YourSentencesAreQuiteLongConsiderBreakingThemIntoShorterOnes:
        "Your sentences are quite long. Consider breaking them into shorter ones.",
    YourSentencesAreVeryShortConsiderCombiningSomeForBetterFlow:
        "Your sentences are very short. Consider combining some for better flow.",
    YourVocabularyDiversityIsLowTryUsingAWiderRangeOfWords:
        "Your vocabulary diversity is low. Try using a wider range of words.",
    YourTextIsWellBalancedConsiderProofreadingForMinorImprovements:
        "Your text is well-balanced. Consider proofreading for minor improvements.",
} as const;
