/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Dialects =
    | "american_english"
    | "australian_english"
    | "british_oxford"
    | "canadian_english"
    | "indian_english";
export const Dialects = {
    AmericanEnglish: "american_english",
    AustralianEnglish: "australian_english",
    BritishOxford: "british_oxford",
    CanadianEnglish: "canadian_english",
    IndianEnglish: "indian_english",
} as const;
