/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

/**
 * Standard error response model.
 */
export interface ErrorResponse {
    error: acrolinx.ErrorDetail;
    /** Accepts any additional properties */
    [key: string]: any;
}
