/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error detail model for consistent error responses.
 */
export interface ErrorDetail {
    code: string;
    message: string;
    description: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
