/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface FinalScores {
    acrolinx_score?: acrolinx.AcrolinxScorerActivityOutput;
    content_score?: acrolinx.ContentScorerActivityOutput;
    issue_score?: acrolinx.IssueScores;
    quality_score?: number;
}
