/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface GrammarChange {
    /** The original text */
    original: string;
    /** The modified text */
    modified: string;
    /** The start index of the change */
    change_start_char_idx: number;
    change_type?: "grammar";
    category: acrolinx.GrammarCategory;
}
