/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface HeliosOneWorkflowOutput {
    /** The date and time the workflow was created */
    created_at: string;
    /** The errors that occurred during the workflow */
    errors?: acrolinx.WorkflowError[];
    /** The initial scores of the workflow */
    initial_scores?: acrolinx.InitialScores;
    /** The final scores of the workflow */
    final_scores?: acrolinx.FinalScores;
    /** The path to the input file */
    input_file: string;
    /** The parameters used to run the workflow */
    parameters?: acrolinx.Parameters;
    /** The Temporal workflow run ID */
    run_id: string;
    /** The Temporal workflow ID */
    workflow_id: string;
    /** The result of the grammar activity */
    grammar_result?: acrolinx.GrammarActivityOutput;
    /** The result of the merging activity */
    merging_result?: acrolinx.MergingActivityOutput;
    /** The result of the parser activity */
    parser_result?: acrolinx.ParserResponse;
    /** The result of the sentence length activity */
    sentence_length_result?: acrolinx.SentenceLengthActivityOutput;
    /** The result of the sentence structure activity */
    sentence_structure_result?: acrolinx.SentenceStructureOutput;
    /** The result of the simple vocabulary activity */
    simple_vocabulary_result?: acrolinx.SimpleVocabOutput;
    /** The result of the tone activity */
    tone_result?: acrolinx.ToneCheckOutput;
    /** The result of the style guide activity */
    style_guide_result?: acrolinx.StyleGuideOutput;
    /** The result of the terminology activity */
    term_replace_result?: acrolinx.TermReplaceActivityOutput;
}
