/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IssueScores {
    grammar_score?: number;
    style_guide_score?: number;
    terminology_score?: number;
    grammar_issues?: number;
    style_guide_issues?: number;
    terminology_issues?: number;
}
