/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface Parameters {
    /** The dialect used for the activity */
    dialect?: acrolinx.Dialects;
    /** The tone used for the activity */
    tone?: acrolinx.Tones;
    /** The style guide used for the activity */
    style_guide?: acrolinx.StyleGuide;
    /** The maximum number of words allowed for the activity */
    max_words?: number;
    /** Formatted string of terms to replace for the activity */
    replace_terms?: string;
    /** Formatted string of terms to not flag for the activity */
    do_not_flag_terms?: string;
}
