/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface RewriteResponse {
    status: acrolinx.StyleGuideStatus;
    scores?: acrolinx.ScoreOutput;
    issues: acrolinx.Suggestion[];
    check_options: acrolinx.CheckOptions;
    rewrite?: string;
    rewrite_scores?: acrolinx.ScoreOutput;
}
