/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Base model for RFC 9457 errors.
 */
export interface Rfc9457Error {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
}
