/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Scores {
    avg_sentence_length: number;
    avg_word_length: number;
    complexity_score: number;
    readability_score: number;
    sentence_count: number;
    vocabulary_score: number;
    word_count: number;
}
