/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface ScoreOutput {
    overall: acrolinx.OverallScore;
    clarity: acrolinx.ClarityScore;
    grammar: acrolinx.GrammarScore;
    style_guide: acrolinx.StyleGuideScore;
    tone: acrolinx.ToneScore;
    terminology: acrolinx.TerminologyScore;
}
