/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface SentenceLengthChange {
    /** The original text */
    original: string;
    /** The modified text */
    modified: string;
    /** The start index of the change (calculated from context) */
    change_start_char_idx?: number;
    change_type?: "sentence_length";
    /** Text that appears before the original text */
    context_before?: string;
    /** Text that appears after the original text */
    context_after?: string;
    category: acrolinx.SentenceLengthCategory;
}
