/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface SentenceLengthActivityOutput {
    /** The hash of the messages used to run the activity */
    msg_hash?: string;
    error?: string;
    /** The duration of the activity in seconds */
    duration: number;
    /** The model used to run the activity */
    model?: string;
    /** The parameters used to run the activity */
    parameters?: acrolinx.Parameters;
    /** The prompt used to run the activity */
    prompt?: Record<string, unknown>;
    /** The completion used to run the activity */
    completion?: Record<string, unknown>;
    /** The provider used to run the activity */
    provider?: string;
    /** The LLM output's JSON repair log for the activity */
    repair_log?: Record<string, string>[];
    run_id: string;
    workflow_id: string;
    text: string;
    changes: acrolinx.SentenceLengthChange[];
}
