/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface StyleGuide {
    /** The type of style guide to use */
    style_guide_type?: acrolinx.StyleGuides;
    /** The ID of the style guide to use */
    style_guide_id?: string;
}
