/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StyleGuideCategory =
    | "punctuation"
    | "capitalization"
    | "grammar_and_usage"
    | "numbers_and_dates"
    | "formatting_and_structure"
    | "other";
export const StyleGuideCategory = {
    Punctuation: "punctuation",
    Capitalization: "capitalization",
    GrammarAndUsage: "grammar_and_usage",
    NumbersAndDates: "numbers_and_dates",
    FormattingAndStructure: "formatting_and_structure",
    Other: "other",
} as const;
