/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface StyleCheckResponse {
    status: acrolinx.StyleGuideStatus;
    scores?: acrolinx.ScoreOutput;
    issues: acrolinx.Issue[];
    check_options: acrolinx.CheckOptions;
}
