/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

/**
 * The sub-category of the change
 */
export type Subcategory =
    | acrolinx.GrammarCategory
    | acrolinx.SimpleVocabCategory
    | acrolinx.SentenceStructureCategory
    | acrolinx.SentenceLengthCategory
    | acrolinx.ToneCategory
    | acrolinx.StyleGuideCategory
    | acrolinx.TermReplaceCategory;
