/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface SuggestionResponse {
    style_guide_id: string;
    scores: acrolinx.Scores;
    issues: acrolinx.Suggestion[];
}
