/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../index";

export interface SuggestionResponse {
    style_guide_id: string;
    scores: Starter.Scores;
    issues: Starter.Suggestion[];
}
