/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Suggestion {
    start_index: number;
    length: number;
    text: string;
    category: string;
    suggestion: string;
}
