/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface SuggestionResponse {
    workflow_id?: string;
    status?: acrolinx.WorkflowStatus;
    scores?: acrolinx.ScoreOutput;
    issues?: acrolinx.Suggestion[];
    check_options?: acrolinx.CheckOptions;
    /** The status code received and URL used when sending the webhook if a webhook URL was included when starting the process. */
    webhook_response?: acrolinx.WebhookResponse;
}
