/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface Suggestion {
    /** The original text */
    original: string;
    /** The start index of the change */
    char_index: number;
    /** The sub-category of the change */
    subcategory: acrolinx.Subcategory;
    suggestion: string;
    category?: acrolinx.IssueCategory;
}
