/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface TheiaOutput {
    errors?: acrolinx.WorkflowError[];
    final_scores?: acrolinx.FinalScores;
    initial_scores?: acrolinx.InitialScores;
    merged_text: string;
    original_text: string;
    results: acrolinx.HeliosOneWorkflowOutput[];
}
