/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Tones =
    | "academic"
    | "business"
    | "casual"
    | "conversational"
    | "formal"
    | "gen-z"
    | "informal"
    | "technical";
export const Tones = {
    Academic: "academic",
    Business: "business",
    Casual: "casual",
    Conversational: "conversational",
    Formal: "formal",
    GenZ: "gen-z",
    Informal: "informal",
    Technical: "technical",
} as const;
