/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface ToneChange {
    /** The original text */
    original: string;
    /** The modified text */
    modified: string;
    /** The start index of the change (calculated from context) */
    change_start_char_idx?: number;
    change_type?: "tone";
    /** Text that appears before the original text */
    context_before?: string;
    /** Text that appears after the original text */
    context_after?: string;
    /** The category of the change */
    category: acrolinx.ToneCategory;
}
