/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface ValidationError {
    loc: acrolinx.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
