/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface WorkflowStatusResponse {
    workflow_id: string;
    status: acrolinx.WorkflowStatus;
    error_message?: string;
    result?: acrolinx.TheiaOutput;
}
