/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../index";

export interface WorkflowResponse {
    status: acrolinx.WorkflowStatus;
    workflow_id: string;
}
