/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../../../../index";

/**
 * @example
 *     {}
 */
export interface StyleRewritesCreateStyleRewriteRequest {
    /** The intended dialect of the text to edit. */
    dialect?: acrolinx.Dialects;
    /** The intended tone of the text to edit. */
    tone?: acrolinx.Tones;
    /** The style guide to use for the text to edit. Can be a style guide ID or the name of a generic style guide, e.g. 'ap', 'chicago', or 'microsoft'. */
    style_guide?: string;
}
