/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         document_id: "document_id"
 *     }
 */
export interface CreateStyleCheckV1StyleChecksPostRequest {
    document_id: string;
}
