/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../../../../index";

/**
 * @example
 *     {
 *         dialect: "american_english",
 *         tone: "academic",
 *         style_guide: "style_guide"
 *     }
 */
export interface StyleChecksCreateStyleCheckRequest {
    /** The language variant you'd like us to use for analysis. Choose from American English, British English, or other supported dialects. */
    dialect: acrolinx.Dialects;
    /** The tone variation you're aiming for. Options include formal, academic, casual, and other tone variations to match your content goals. */
    tone: acrolinx.Tones;
    /** The style guide to follow for your content. You can use a style guide ID or choose from built-in options: `ap`, `chicago`, or `microsoft`. */
    style_guide: string;
}
