/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as acrolinx from "../../../index";

export type StyleRewritesGetStyleRewriteResponse =
    | acrolinx.RewriteResponse
    | acrolinx.WorkflowStatusResponse
    | acrolinx.StyleCheckResponse
    | acrolinx.Rfc9457Error;
