/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const acrolinxEnvironment = {
    Default: "http://helios.api.localhost",
} as const;

export type acrolinxEnvironment = typeof acrolinxEnvironment.Default;
