/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const acrolinxEnvironment = {
    Production: "https://api.acrolinx.com",
} as const;

export type acrolinxEnvironment = typeof acrolinxEnvironment.Production;
