/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const acrolinxEnvironment = {
    Default: "https://app.acrolinx.cloud",
} as const;

export type acrolinxEnvironment = typeof acrolinxEnvironment.Default;
